name: wenda_gpu_paper

channels:
- conda-forge
dependencies:
- conda-forge::python=3.7
- conda-forge::pytorch=1.9
- conda-forge::torchvision=0.10.1
- conda-forge::cudatoolkit=10.2
- conda-forge::numpy=1.20
- conda-forge::pandas=1.2.5
- conda-forge::gpytorch=1.5.1
- conda-forge::gpy=1.10.0
- conda-forge::ipython=7.28.0
- conda-forge::tqdm=4.62.3
- conda-forge::glmnet=2.2.1
- conda-forge::scipy=1.7.1
- conda-forge::matplotlib=3.3.4
- conda-forge::scikit-learn=0.24.2
- conda-forge::statsmodels=0.13.2
- conda-forge::plotnine=0.8.0
- conda-forge::svgutils=0.3.0
